version: '3.8'

services:
  postgresql:
    image: postgres:latest
    volumes:
      - ./pgsql/database:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: tracker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret

      TZ: 'Europe/Moscow'
    ports:
      - 5432:5432

  mailhog:
    image: mailhog/mailhog:latest
    logging:
      driver: 'none'
    ports:
      - 1025:1025 # smtp
      - 8025:8025 # web